update project config

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -15,8 +15,16 @@ on:
     paths-ignore:
     - '**/*.adoc'
     - '**/*.md'
+    - '.editorconfig'
+    - '.git*'
     - '.github/*.yml'
   pull_request:
+    paths-ignore:
+    - '**/*.adoc'
+    - '**/*.md'
+    - '.editorconfig'
+    - '.git*'
+    - '.github/*.yml'
   workflow_dispatch:
     # https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
     inputs:
@@ -24,57 +32,75 @@ on:
         description: 'Additional Maven Args'
         required: false
         default: ''
+      debug-with-ssh:
+        description: "Start an SSH session for debugging purposes at the end of the build:"
+        default: never
+        type: choice
+        options: [ always, on_failure, on_failure_or_cancelled, never ]
+      debug-with-ssh-only-for-actor:
+        description: "Limit access to the SSH session to the GitHub user that triggered the job."
+        default: true
+        type: boolean
 
 defaults:
   run:
     shell: bash
 
+
 jobs:
 
-  build:
+  ###########################################################
+  maven-build:
+  ###########################################################
     runs-on: ubuntu-latest
+
+    # https://docs.github.com/en/actions/using-jobs/using-concurrency
     concurrency: ci-${{ github.ref }}
+
     steps:
     - name: Show environment variables
       run: env | sort
 
+
     - name: Git Checkout
       uses: actions/checkout@v4 # https://github.com/actions/checkout
 
-    - name: Set up JDK 11
+
+    - name: "Install: JDK 11"
       uses: actions/setup-java@v4 # https://github.com/actions/setup-java
       with:
         distribution: temurin
         java-version: 11
     - run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV
 
-    - name: Set up JDK 17
+
+    - name: "Install: JDK 17"
       uses: actions/setup-java@v4 # https://github.com/actions/setup-java
       with:
         distribution: temurin
         java-version: 17
     - run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV
 
-    - name: "Cache: Local Maven Repository"
-      uses: actions/cache@v3
+
+    - name: "Cache: Restore"
+      id: cache-restore
+      if: ${{ !env.ACT }} # https://github.com/nektos/act#skipping-steps
+      uses: actions/cache/restore@v3
       with:
         path: |
+          ~/.m2/bin
           ~/.m2/repository
-          !~/.m2/**/*SNAPSHOT*
-        key: ${{ runner.os }}-mvnrepo-${{ hashFiles('**/pom.xml') }}
-        restore-keys: |
-          ${{ runner.os }}-mvnrepo-
+        key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
 
-    - name: Set up Maven
-      uses: stCarolas/setup-maven@v4.5
-      with:
-        maven-version: 3.9.5
 
     - name: Test with Maven
       id: maven-test
-      if: ${{ github.ref_name != 'main' }}
+      if: ${{ github.ref_name != 'main' || env.ACT }}
+      env:
+        MAY_CREATE_RELEASE: false
       run: |
         bash .ci/build.sh ${{ github.event.inputs.additional_maven_args }}
+
 
     - name: Prepare Maven Snapshots Repo
       if: ${{ github.ref_name == 'main' }}
@@ -113,9 +139,10 @@ jobs:
           git commit -am "Initialize Maven Snapshots Repo"
         fi
 
+
     - name: Build with Maven
       id: maven-build
-      if: ${{ github.ref_name == 'main' }}
+      if: ${{ github.ref_name == 'main' && !env.ACT }}
       env:
         MAY_CREATE_RELEASE: true
         SIGN_KEY: ${{ secrets.GPG_SIGN_KEY }}
@@ -132,6 +159,7 @@ jobs:
           ${{ github.event.inputs.additional_maven_args }} \
           -DaltSnapshotDeploymentRepository=temp-snapshots-repo::default::file:///tmp/mvn-snapshots-repo
 
+
     - name: Update Maven Snapshots Repo
       if: ${{ github.ref_name == 'main' }}
       run: |
@@ -143,10 +171,66 @@ jobs:
         fi
 
 
+    ##################################################
+    # Cache Update
+    # See https://github.com/actions/cache/issues/342
+    ##################################################
+    - name: "Cache: Delete Previous"
+      if: ${{ steps.cache-restore.outputs.cache-hit && !env.ACT }}
+      env:
+        GH_TOKEN: ${{ github.token }}
+      run: |
+        gh extension install actions/gh-actions-cache
+        # "|| true" is to avoid "Error: Resource not accessible by integration" from failing the job 
+        gh actions-cache delete ${{ steps.cache-restore.outputs.cache-primary-key }} --confirm || true
+
+    - name: "Cache: Update"
+      uses: actions/cache/save@v3
+      if: ${{ always() && !cancelled() && !env.ACT }} # save cache even fails
+      with:
+        path: |
+          ~/.m2/bin
+          ~/.m2/repository
+          !~/.m2/repository/com/vegardit/maven
+          !~/.m2/repository/*SNAPSHOT*
+        key: ${{ steps.cache-restore.outputs.cache-primary-key }}
+
+
+    ##################################################
+    # Setup SSH debug session
+    ##################################################
+    - name: "SSH session for debugging: check"
+      id: DEBUG_SSH_SESSSION_CHECK
+      if: always()
+      run: |
+        set -eu
+
+        when="${{ inputs.debug-with-ssh }}"
+
+        if [[ $when == "always" ]] || case "${{ job.status }}" in
+          success)   [[ $when == "always" ]] ;;
+          cancelled) [[ $when == "on_failure_or_cancelled" ]] ;;
+          failure)   [[ $when == "on_failure"* ]] ;;
+        esac; then
+          echo "start_ssh_session=true" | tee -a "$GITHUB_OUTPUT"
+        fi
+
+
+    - name: "SSH session for debugging: start"
+      uses: mxschmitt/action-tmate@v3 # https://github.com/mxschmitt/action-tmate
+      if: always() && steps.DEBUG_SSH_SESSSION_CHECK.outputs.start_ssh_session
+      with:
+        limit-access-to-actor: ${{ inputs.debug-with-ssh-only-for-actor }}
+
+
+  ###########################################################
   dependabot-pr-auto-merge:
-    needs: build
+  ###########################################################
+    needs: maven-build
     if: ${{ github.event_name == 'pull_request' && github.actor == 'dependabot[bot]' }}
     runs-on: ubuntu-latest
+
+    concurrency: dependabot-pr-auto-merge
 
     permissions:
       contents: write
@@ -158,6 +242,7 @@ jobs:
       uses: dependabot/fetch-metadata@v1 # https://github.com/dependabot/fetch-metadata/
       with:
         github-token: "${{ secrets.GITHUB_TOKEN }}"
+
 
     - name: Enable auto-merge for Dependabot PRs
       if: |
