ci: update workflow config

diff --git a/.github/workflows/update-eea-files.yml b/.github/workflows/update-eea-files.yml
--- a/.github/workflows/update-eea-files.yml
+++ b/.github/workflows/update-eea-files.yml
@@ -18,9 +18,11 @@ on:
         required: false
         default: ''
 
+
 defaults:
   run:
     shell: bash
+
 
 jobs:
 
@@ -30,41 +32,53 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Show environment variables
+    - name: "Show: GitHub context"
+      env:
+        GITHUB_CONTEXT: ${{ toJSON(github) }}
+      run: echo $GITHUB_CONTEXT
+
+
+    - name: "Show: environment variables"
       run: env | sort
 
 
     - name: Git Checkout
-      uses: actions/checkout@v4 # https://github.com/actions/checkout
+      uses: actions/checkout@v4  # https://github.com/actions/checkout
 
 
-    - name: "Install: JDK 11"
-      uses: actions/setup-java@v4 # https://github.com/actions/setup-java
+    - name: "Install: JDK 11 ☕"
+      id: setup-java-11
+      uses: actions/setup-java@v4  # https://github.com/actions/setup-java
       with:
         distribution: temurin
         java-version: 11
-    - run: echo "JAVA11_HOME=$JAVA_HOME" >> $GITHUB_ENV
 
 
-    - name: "Install: JDK 17"
-      uses: actions/setup-java@v4 # https://github.com/actions/setup-java
+    - name: "Install: JDK 17 ☕"
+      id: setup-java-17
+      uses: actions/setup-java@v4  # https://github.com/actions/setup-java
       with:
         distribution: temurin
         java-version: 17
-    - run: echo "JAVA17_HOME=$JAVA_HOME" >> $GITHUB_ENV
 
 
-    - name: "Install: JDK 21"
-      uses: actions/setup-java@v4 # https://github.com/actions/setup-java
+    - name: "Install: JDK 21 ☕"
+      id: setup-java-21
+      uses: actions/setup-java@v4  # https://github.com/actions/setup-java
       with:
         distribution: temurin
         java-version: 21
-    - run: echo "JAVA21_HOME=$JAVA_HOME" >> $GITHUB_ENV
+
+
+    - name: Set JAVA_HOME env vars
+      run: |
+        echo "JAVA11_HOME=${{ steps.setup-java-11.outputs.path }}" >> $GITHUB_ENV
+        echo "JAVA17_HOME=${{ steps.setup-java-17.outputs.path }}" >> $GITHUB_ENV
+        echo "JAVA21_HOME=${{ steps.setup-java-21.outputs.path }}" >> $GITHUB_ENV
 
 
     - name: "Cache: Restore"
       id: cache-restore
-      if: ${{ !env.ACT }} # https://github.com/nektos/act#skipping-steps
       uses: actions/cache/restore@v4
       with:
         path: |
@@ -73,14 +87,14 @@ jobs:
         key: ${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
 
 
-    - name: Update EEA Files
+    - name: "Update EEA Files 🔨"
       id: eea_updates
       run: |
         set -euo pipefail
 
         bash .ci/update-eea-files.sh ${{ github.event.inputs.additional_maven_args }}
 
-        updates=$(git -C . ls-files -o -m -d --exclude-standard)
+        updates=$(git -C . ls-files -o -m -d --exclude-standard | head -n 50 || true)  # "|| true" is to mitgate exit code 141
 
         if [[ -z $updates ]]; then
           echo "updates=" >> "$GITHUB_OUTPUT"
@@ -95,7 +109,7 @@ jobs:
 
     - name: Create PR
       id: create-pr
-      uses: peter-evans/create-pull-request@v6 # https://github.com/peter-evans/create-pull-request
+      uses: peter-evans/create-pull-request@v6  # https://github.com/peter-evans/create-pull-request
       if: "${{ steps.eea_updates.outputs.updates != '' }}"
       with:
         title: "chore: Update EEA Files"
